### PR TITLE
Handle invalid GitHub token

### LINKED ISSUE #24: Handle invalid GITHUB_TOKEN
Similar to #23. This issue happens when the `GITHUB_TOKEN` environment variable is set to a wrong value (invalid or expired token).

Example from `dune utop`:

```ocaml
utop # Sys.getenv "GITHUB_TOKEN" ;;
- : string = "foo"

utop # Gh.Client.query "query { viewer { login } }" ;;
- : string =
"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/graphql\",\"status\":\"401\"}"
```

Depending on whether #23 will be done first, this issue is similar: introduce new error type `Bad_credentials` and handle it in this function.

This will require changing the return type of `Client.query` from `string` to `Yojson.Basic.t` but this is fine.

### PR DESCRIPTION
**Pull request by loadre**
closes #24

### CODE REVIEW

**Comment by chshersh** [comment]
@heathhenley @loadre I've added you both as collaborators.

Since we're starting to work more on this together, feel free to review PRs of each other as well. It's a nice practice 🙂 
Also good for knowledge sharing about the project.

I haven't really invested a lot into making this project contributable. I'll add proper Code of Conduct and Contributing guide soon, so there'll be less uncertainty about future of this project and conflict resolution.

**Comment by chshersh** [comment]
@qexat Since you made a contribution, it now applies to you as well 😅 No pressure!

File: lib/gh/client.ml [hunk 1]
```diff
@@ -25,12 +26,16 @@ let query query_body =
       in
       match response with
       | Error (code, msg) -> Error (Curl_error { code = Curl.errno code; msg })
-      | Ok response -> Ok response.body)
+      | Ok { body; _ } ->
```
Comment (qexat) [inline lib/gh/client.ml]: Huh, GitHub sends an Ok response on bad credentials?

File: lib/gh/client.ml [hunk 2]
```diff
@@ -2,6 +2,7 @@ module Json = Yojson.Basic.Util
 
 type error =
   | No_github_token
+  | Bad_credentials
```
Comment (chshersh) [inline lib/gh/client.ml]: My only feedback: let's create the `bad_credentials` error type and put the message, documentation url and status code inside this type and decode it from JSON:

```ocaml
"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/graphql\",\"status\":\"401\"}"
```

And then display this information in the UI. Let's try to avoid loosing potentially useful debugging information.

Also, I'm not sure if "Bad credentials" is the only possible message. At least, if we display the message, we'll be able to learn about different error scenarios

**Comment by heathhenley** [comment]
Pulled it down to test, looks great with no token and with a bad token 🚀

File: lib/gh/client.ml (hunk 1 above)
Comment (loadre) [reply lib/gh/client.ml]:
```
utop # let query token query_body =
Ezcurl.post ~params:[]
~headers:[
("Authorization", "bearer " ^ token);
]
~content:(`String (Printf.sprintf "{ \"query\": %S }" query_body))
~url:"https://api.github.com/graphql" ()
;;
val query :
  string -> string -> (Ezcurl.response, Curl.curlCode * string) result = <fun>
utop # query "foo" "query { viewer { login } }";;
- : (Ezcurl_core.response, Curl.curlCode * string) result =
Ok
 {Ezcurl_core.code = 401;
  ...
  body =
   "{\n  \"message\": \"Bad credentials\",\n  \"documentation_url\": \"https://docs.github.com/graphql\",\n  \"status\": \"401\"\n}\n";
 ...}
```
Github API sends 401 with plain HTTP request with curl, I think this might have something to do with how Ezcurl handles responses.

File: lib/gh/client.ml [hunk 3]
```diff
@@ -25,12 +30,21 @@ let query query_body =
       in
       match response with
       | Error (code, msg) -> Error (Curl_error { code = Curl.errno code; msg })
-      | Ok response -> Ok response.body)
+      | Ok { body; code; _ } ->
+          let open Yojson.Basic in
+          let json = from_string body in
+          if Util.member "data" json <> `Null then Ok json
```
Comment (loadre) [inline lib/gh/client.ml:36]: This part assumes that if `response.body` doesn't contain `data`, then it must contain `message` and `documentation_url`, which I'm not sure is a good decision or not.

Edit:
Just tested with malformed GQL query, got responses in the form of `{"errors": [...]}`. Maybe it deserves having its own issue (later on)?

File: lib/gh/client.ml (hunk 1 above)
Comment (chshersh) [reply lib/gh/client.ml]: @loadre Thanks for providing the example! I didn't know this about the internals of `ezcurl`.

File: lib/gh/client.ml (hunk 3 above)
Comment (chshersh) [reply lib/gh/client.ml:36]: > This part assumes that if response.body doesn't contain data, then it must contain message and documentation_url, which I'm not sure is a good decision or not.

Sounds good to me. Let's stick to it for now. We can always refine later.

> Just tested with malformed GQL query, got responses in the form of {"errors": [...]}. Maybe it deserves having its own issue (later on)?

Yes, please! Feel free to create a separate issue. It's a good idea to handle such errors as well.

**Review by chshersh — APPROVED** [review]
Thank you!
